### ISSUE TITLE
Missing assemblies when building from source

### ISSUE THREAD

**Issue by Raekh** [FlawTECH/CWissKnife#6]
The following assemblies are missing when trying to build:
- Assembly-CSharp
- PhotoUnityNetworking
- Zorro.Settings.Runtime

**Comment by FlawTECH** [comment]
Hi, you need to add these assemblies to the project yourself (for copyright reasons, I cannot publish these binaries on Github). These assemblies can be found in the game's installation folder. By default, on Windows, they can be found in `C:\Program Files (x86)\Steam\steamapps\common\Content Warning\Content Warning_Data\Managed`. If you want minimal effort, I advise you put them where they are expected, in `$PROJECT_DIR\libs`. Otherwise, you would have to edit the `.csproj` file to point to the correct location.
